# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Название группы')),
            ],
        ),
        migrations.CreateModel(
            name='Raspisanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(blank=True, default=0, max_length=4, verbose_name='Номер аудитории')),
                ('subgroup', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=2, verbose_name='Номер подгруппы')),
                ('course', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=2, verbose_name='Курс')),
                ('subject_type', models.CharField(choices=[('лекция', 'лекция'), ('практика', 'практика'), ('лабораторная', 'лабораторная')], default=1, max_length=20, verbose_name='Тип пары')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=0, verbose_name='День недели')),
                ('type_of_week', models.CharField(choices=[('Верхняя', 'Верхняя'), ('Нижняя', 'Нижняя'), ('Верхняя и нижняя', 'Верхняя и нижняя')], default=1, max_length=20, verbose_name='Тип недели')),
                ('time', models.CharField(choices=[('8:15', '8:15'), ('10:00', '10:00'), ('11:45', '11:45'), ('13:30', '13:30'), ('15:15', '15:15'), ('17:00', '17:00'), ('18:45', '18:45')], default=1, max_length=10, verbose_name='Время начала')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbot.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ФИО')),
            ],
        ),
        migrations.AddField(
            model_name='raspisanie',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbot.Subject'),
        ),
        migrations.AddField(
            model_name='raspisanie',
            name='teacher',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='vbot.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='raspisanie',
            unique_together=set([('subject', 'teacher', 'group', 'classroom', 'subgroup', 'course', 'subject_type', 'weekday', 'type_of_week', 'time')]),
        ),
    ]
